runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
env_variables:
    CLOUD_STORAGE_BUCKET: dicoding-submission-gcp01.appspot.com